name: Docker Build

on:
  push:
    branches:
      - develop


jobs:
  analyze:
    name: SonarQube analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Analyse sonar
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build Backend Image
        run: |
          cd backend
          docker build \
            -t my-backend:latest

  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build Frontend Image
        run: |
          cd frontend
          docker build \
            --build-arg HTTP_PROXY=$HTTP_PROXY \
            --build-arg HTTPS_PROXY=$HTTPS_PROXY \
            -t my-frontend:latest
